<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE reservations [
<!ELEMENT reservations (reservation)*>
<!ELEMENT reservation (ID , start_time , duration , res_date , res_text , user_ID , room_ID)>
<!ELEMENT ID (#PCDATA)>
<!ELEMENT start_time (#PCDATA)>
<!ELEMENT duration (#PCDATA)>
<!ELEMENT res_date (#PCDATA)>
<!ELEMENT res_text (#PCDATA)>
<!ELEMENT user_ID (#PCDATA)>
<!ELEMENT room_ID (#PCDATA)>
]>
<reservations>
  <reservation>
    <ID>17</ID>
    <start_time/>
    <duration/>
    <res_date>07.05.2013</res_date>
    <res_text>Sepon varaus</res_text>
    <user_ID>3</user_ID>
    <room_ID>15</room_ID>
  </reservation>
</reservations>
