<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE reservations [
<!ELEMENT reservations (reservation)*>
<!ELEMENT reservation (ID , start_time , duration , res_date , res_text , user_ID , room_ID)>
<!ELEMENT ID (#PCDATA)>
<!ELEMENT start_time (#PCDATA)>
<!ELEMENT duration (#PCDATA)>
<!ELEMENT res_date (#PCDATA)>
<!ELEMENT res_text (#PCDATA)>
<!ELEMENT user_ID (#PCDATA)>
<!ELEMENT room_ID (#PCDATA)>
]>
<reservations>
  <reservation>
    <ID>25</ID>
    <start_time/>
    <duration/>
    <res_date>08.05.2013</res_date>
    <res_text>999</res_text>
    <user_ID>1</user_ID>
    <room_ID>14</room_ID>
  </reservation>
  <reservation>
    <ID>26</ID>
    <start_time/>
    <duration/>
    <res_date>23.05.2013</res_date>
    <res_text>9999999</res_text>
    <user_ID>1</user_ID>
    <room_ID>14</room_ID>
  </reservation>
  <reservation>
    <ID>28</ID>
    <start_time/>
    <duration/>
    <res_date>26.05.2013</res_date>
    <res_text>asd</res_text>
    <user_ID>2</user_ID>
    <room_ID>14</room_ID>
  </reservation>
  <reservation>
    <ID>30</ID>
    <start_time/>
    <duration/>
    <res_date>01.05.2013</res_date>
    <res_text>1 varaus</res_text>
    <user_ID>1</user_ID>
    <room_ID>5</room_ID>
  </reservation>
  <reservation>
    <ID>31</ID>
    <start_time/>
    <duration/>
    <res_date>02.05.2013</res_date>
    <res_text>2 varaus</res_text>
    <user_ID>2</user_ID>
    <room_ID>5</room_ID>
  </reservation>
</reservations>
