<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE reservations [
<!ELEMENT rss (item)*>
<!ELEMENT item (title , link , description)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT link (#PCDATA)>
<!ELEMENT description (#PCDATA)>
]>
<rss>
  <item>
    <title>07.05.2013</title>
    <link>http://localhost/Roomservice/app/</link>
    <description>ottoki has reserved room no. 8</description>
  </item>
</rss>
